### ISSUE TITLE
[Feature Request] More message cooldown functionality/customization

### ISSUE THREAD

**Issue by thunder-red-star** [nulli0n/SunLight-spigot#49]
Chat module feels very well developed but one thing that would be quite useful would be a way to enforce per-group chat cooldowns. For example players who have ranks can have a lower (but not completely removed) chat cooldown. Also if we can customize the message when user is trying to send their message before their cooldown, that would be nice (if this doesn't already exist).

Example configuration:
```yaml
global:
  Name: '&6Global'
  Default: true
  Auto_Join: false
  Permission_Required:
    Hear: false
    Speak: false
  Radius: -1
  Command_Alias: global
  Message_Prefix: ''

  # Permission: sunlight.chat.channel.cooldown.[channelId].[groupId]
  # Example: sunlight.chat.channel.cooldown.global.vip
  Message_Cooldown:
   default: 3
   vip: 2
   elite: 1
   moderator: 0
  Message_Cooldown_Message: '&cWait %remaining% seconds before sending another message or purchase a rank to remove your %cooldown% second cooldown.'
  # in this case, %remaining% represents the remaining time in seconds before the player can send another message (e.g. 1.4 seconds)
  # and %cooldown% represents the cooldown time in seconds (e.g. 3 seconds)

  Format: '&7%format_player_name%%format_player_color%: %format_player_message%'
```
