### ISSUE TITLE
[Bug] 1.20.6 | List Formatting not working

### ISSUE THREAD

**Issue by CaptnLucid** [nulli0n/SunLight-spigot#72]
List formatting doesn't seem to be working appropriately when it comes to detecting ranks. I have LuckPerms installed and have changed my user's rank to the 3 different ones available.

```yaml
List:
    owner:
      Priority: 10
      Name: "%rank_owner%%player_info%: "
      Message: "%msg%"
      Ranks:
        - owner
        - admin
    admin:
      Priority: 9
      Name: "%user_tag%%rank_member%%user_admin% &8» "
      Message: "%msg%"
      Ranks:
        - admin
    default:
      Priority: 0
      Name: "%user_tag%%rank_member%%user_default% &8» "
      Message: "%msg%"
      Ranks:
        - "*"
```

The `default` takes priority. If i change the group to `default` instead of `'*'`, I receive this as an error.

`[18:54:56 ERROR]: [SunLight] [Chat] Could not handle message from 'LucidiousXIV': No format is available!`

The formatting only applies if the ranks have the `'*'` field

Loading the prefix from LuckPerms works perfectly fine, so it seems to be an issue with pulling the rank itself.
